CREATE TABLE IF NOT EXISTS "Food" (
	"name" TEXT NULL DEFAULT NULL,
	"price" MONEY NULL DEFAULT NULL,
	"contents" REAL NULL DEFAULT NULL,
	"contentsUnit" TEXT NULL DEFAULT NULL,
	"ingredientMatches" JSON NULL DEFAULT NULL,
	"store" TEXT NULL DEFAULT NULL,
	UNIQUE ("name")
);